# Documentation for the sass-lint Linters is available at:
# https://github.com/sasstools/sass-lint/tree/develop/docs/rules
files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedbem
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  indentation:
    - size: 2
  force-element-nesting: 0
  mixins-before-declarations:
    exclude:
      - respond-to
      - breakpoint
      - mq
  nesting-depth:
    - 1
    - max-depth: 4
  no-important: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties:
        - '*background'
        - '*background-image'
        - '*display'
        - '*font-family'
        - _font-family
        - '*height'
        - '*list-style-image'
        - '*margin-left'
        - '*margin-right'
        - '*overflow'
        - '*position'
        - '*vertical-align'
        - '*width'
        - '*zoom'
  no-qualifying-elements: 0
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
  space-after-colon: 1
  space-between-parens: 0
  quotes:
    style: single
