version: "3"

services:
  app:
    image: previousnext/php:7.2-dev
    # You will notice that we are forwarding port which do not belong to PHP.
    # We have to declare them here because these "sidecar" services are sharing
    # THIS containers network stack.
    ports:
      - "80:80"
      - "3306:3306"
      - "8983:8983"
      - "8025:8025"
      - "8910:8910"
    volumes:
      - .:/data:cached
      # This allows for developers to access the remote environment.
      - $HOME/.ssh:/root/.ssh
      # Mount skpr credentials.
      - $HOME/.skpr.yml:/root/.skpr.yml
      # Mount composer cache.
      - $HOME/.composer:/root/.composer
    environment:
      - MINK_DRIVER_ARGS=["http:\/\/127.0.0.1:8510", "\/tmp"]
      - XDEBUG_CONFIG=remote_host=docker.for.mac.host.internal remote_connect_back=0
      - PHP_IDE_CONFIG=serverName=localhost

  db:
    image: mariadb
    network_mode: service:app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal

#  varnish:
#    image: previousnext/varnish:4.x-dev
#    network_mode: service:app

#  memcache:
#    image: memcached:1.4-alpine
#    network_mode: service:app

  mail:
    image: mailhog/mailhog
    network_mode: service:app

#  phantomjs:
#    image: previousnext/gastonjs:1.0.2
#    network_mode: service:app

#  search:
#    image: previousnext/solr:5.x
#    network_mode: service:app

#  blackfire:
#    # See https://redmine.previousnext.com.au/projects/pnx-local/wiki/Docker_and_Blackfire
#    image: blackfire/blackfire
#    environment:
#      BLACKFIRE_SERVER_ID: YOUR_SERVER_ID_HERE
#      BLACKFIRE_SERVER_TOKEN: YOUR_SERVER_TOKEN_HERE

  # This is a regularly scheduled job which enables local cron tasks.
  #  * Gosu = Run as a user (www-data) to avoid permissions issues.
  #  * Microcron = Our project which ensures cron will run every 5min.
#  cron-drush:
#    image: previousnext/php:7.2-dev
#    entrypoint: ['gosu', 'www-data', 'microcron', '5m', 'drush cron']
#    network_mode: service:app
#    volumes:
#      - .:/data
